version: '3.8'

services:
  codeconnect-frontend:
    image: maxin0525/codeconnect-frontend:latest
    container_name: codeconnect-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
